### ISSUE TITLE
"cx11" is not a recognised standard

### ISSUE THREAD

**Issue by deeuu** [lamyj/homebrew-odil#1]
Hi,

I'm trying to install `odil` via brew on macOS Catalina, and get this:

```
brew tap lamyj/odil
==> Tapping lamyj/odil
Cloning into '/usr/local/Homebrew/Library/Taps/lamyj/homebrew-odil'...
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 5 (delta 0), reused 4 (delta 0), pack-reused 0
Unpacking objects: 100% (5/5), done.
odil: "cxx11" is not a recognized standard
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/lamyj/homebrew-odil/HomebrewFormula/odil.rb
Error: Cannot tap lamyj/odil: invalid syntax in tap!
```

Looks like an issue with [this line](https://github.com/lamyj/homebrew-odil/blob/master/HomebrewFormula/odil.rb#L20)?

**Comment by lamyj** [comment]
This seems to have been deprecated almost a year ago: Homebrew/brew@1aa8ad09e212cd9cd2f3ae55f899ed4ef03ae4d0

Should be fixed in fdeee91, although I don't have a Catalina box available: could you confirm this issue is solved? I also took the opportunity to bump the version number in the latest revision.

**Comment by deeuu** [comment]
Hey,

I can now add the tap, but receive the following build error on `brew install odil`:
```
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/odil/0.10.0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -GNinja -DBUILD_PYTHON_WRAPPERS=ON -DPYTHON_EXECUTABLE=/us
Last 15 lines from /Users/deeuu/Library/Logs/Homebrew/odil/01.cmake:

  Could not find a package configuration file provided by "pybind11" with any
  of the following names:

    pybind11Config.cmake
    pybind11-config.cmake

  Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
  "pybind11_DIR" to a directory containing one of the above files.  If
  "pybind11" provides a separate development package or SDK, be sure it has
  been installed.
```

**Comment by lamyj** [comment]
I've update the dependencies in 8eb081b. The installation works on my Sierra box, I just hope I didn't forget additional dependencies. If further errors appear, I'll check with my colleagues to see if I can get my hands on a Catalina install.

**Comment by deeuu** [comment]
Thanks - managed to install.

Now, after running `odil` I receive an `ImportError`:
```
Traceback (most recent call last):
  File "/usr/local/bin/odil", line 7, in <module>
    import odil.cli
  File "/usr/local/lib/python3.7/site-packages/odil/__init__.py", line 4, in <module>
    from ._odil import *
ImportError: dlopen(/usr/local/lib/python3.7/site-packages/odil/_odil.so, 2): Symbol not found: __ZN5boost3log11v2_mt_posix11record_view11public_data7destroyEPKS3_
  Referenced from: /usr/local/Cellar/odil/0.10.0/lib/libodil.0.dylib
  Expected in: flat namespace
 in /usr/local/Cellar/odil/0.10.0/lib/libodil.0.dylib
```

Let me know if you want me to report this one on the [odil repo](https://github.com/lamyj/odil).

**Comment by lamyj** [comment]
I think this is related to Homebrew/homebrew-core#44093, which is still open as of today. The fix they mention has been implemented in 8b795d9: with this latest release, the logging seems to work.

Forcing a logging message can be done with (assuming [Medical Connections's public server](https://www.medicalconnections.co.uk/kb/Public-DICOM-Server) is up and reachable):
```shell
host:homebrew-odil user$ odil echo -v info www.dicomserver.co.uk  11112 myself dicomserver
INFO:root:Association established
INFO:root:C-ECHO successful
INFO:root:Association released
```
